# Generated by Django 6.1.1 on 2026-10-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_institution_medicalsupply_supplycategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalsupply',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
